name: Collect Cyber News

on:
  schedule:
    # Run 4 times daily: 6 AM, 12 PM, 6 PM, 11 PM UTC
    # Covers morning, midday, evening, and late-night threat disclosures
    - cron: '0 6,12,18,23 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

# Principle of least privilege — only read repo contents
permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sentence-transformers
      
      - name: Run collector
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python collector_mdr.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: collection-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7
