name: Collect Cyber News

on:
  schedule:
    # Run 3 times daily: 6 AM, 12 PM, 6 PM UTC
    - cron: '0 6,12,18 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai sentence-transformers supabase feedparser requests
      
      - name: Run collector
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python collector.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: collection-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7
